#Kubernetes service for Portfolio Web App
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    app: portfolio
spec:
  type: NodePort
  ports:
  - name: portfolio-service
    port: 80
    targetPort: 80
    nodePort: 30090
  selector:
    app: portfolio